head.load("js/lib/jquery.js",
		  "js/lib/jquery-ui.min.js",
		  "js/lib/jquery.ui.touch-punch.js",
		  "js/lib/slick.min.js",
		  "js/lib/picturefill.min.js",
		  "js/lib/jquery.fullPage.min.js",
		  "js/lib/jquery.oembed.js",
		  "js/lib/jquery.mousewheel.min.js", 
		  "js/common.js");
